---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: de-916-ping-pkuorewxs-0-0-0-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./de-916-ping-pkuorewxs-0-0-0
  prune: true
  sourceRef:
    kind: GitRepository
    name: de-916-ping-pkuorewxs-0-0-0-source
  targetNamespace: default

